### PR TITLE
Added ability to change text color of title and subtitle programmatically and in xml.

### PR DESCRIPTION
**Pull request by bropane**

### CODE REVIEW

**Comment by xiprox** [comment]
Hi, thanks for contributing! I really appreciate that you followed the general code format too.

One thing though, are you sure it works with `setColor(int res)` when you want to use a color resources? I think it should be something like `setColor(context.getResources.getColor(int res))`. 

We don't really need to get colors from resources in ErrorView though. We could just have `setColor(int color)` methods and the users would get colors from resources before passing them to ErrorView.

**Comment by bropane** [comment]
I made some name changes and added the changes you requested.

**Comment by xiprox** [comment]
Oh, I think I couldn't make my point clear. I think it's a better idea to use color ints directly for setColor methods. As for the reason, not always would a user want to use colors from resources. There may be cases when colors generated at runtime may be desired to be used. The methods would look like
```java
setColor(int color) {
    mView.setTextColor(color);
}
```
If anyone wants to use a resource, they'd have to do something like the following:
```java
mErrorView.setErrorTitleColor(context.getResources(getColor(R.color.some_color)));
```

**Comment by xiprox** [comment]
Ok, seems good. Thanks again!

**Comment by bropane** [comment]
Np, happy to help

**Pull request merged**
